// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testcase3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testcase3() {
    driver.get("https://worldoftanks.ru/ru/ratings/");
    driver.manage().window().setSize(new Dimension(1616, 876));
    driver.findElement(By.cssSelector(".js-mainmenu-item:nth-child(6) > .nav-submenu_link")).click();
    driver.findElement(By.cssSelector(".b-context-menu-list > li:nth-child(4) span")).click();
    driver.findElement(By.cssSelector(".b-img-signature:nth-child(5) .b-icon-video")).click();
    driver.findElement(By.cssSelector(".cm-singletons:nth-child(2) > .cm-singletons_text")).click();
    driver.findElement(By.cssSelector(".js-cm-tooltip-services")).click();
  }
}
